### ISSUE TITLE
Typing.IO problem when migrating from Python 3.6 to Python 3.10

### ISSUE THREAD

**Issue by mateoradman** [python/typing#1162]
Hi everyone, 

Upon updating from python 3.6 to python 3.10, type hint `IO[bytes]` fails due to: 
```python
TypeError: 'type' object is not subscriptable
```

Example:
```python
from typing import Any, IO
def func(arg: Any) -> IO[bytes]:
    ...
```
Why is this happening?
There is no mention that the typing.IO is not subscriptable anymore in the official python 3.10 documentation.

System information:
Ubuntu 20.04
Python 3.10.4

Thanks.

EDIT:
Very important thing I might've missed to mention is that the wheel that I tested with is cythonized.

**Comment by mateoradman** [comment]
Thank you for your quick response, much appreciated.
I was able to confirm that the problem is indeed related to cython and not to python/typing.
I created a file test_typing.py with the following code:
```python
from typing import IO

def func() -> IO[bytes]:
    ...
```

After executing `python3.10 test_typing.py` the code ran through without any errors. 
Then, I executed `cythonize -ai test.py` to cythonize this individual file, moved the original test_typing.py somewhere else and ran 
```shell
python3.10 -c "from test_typing import func"

Traceback (most recent call last):
File "<string>", line 1, in <module>
  File "test_typing.py", line 4, in init test_typing
TypeError: 'type' object is not subscriptable
``` 
I think this is self-explanatory and I will close the issue now. Hope this issue helps someone else who runs into the same problem.

Thank you and have a nice day 😃
