### ISSUE TITLE
Backport generic NamedTuple and TypedDict support

### ISSUE THREAD

**Issue by JelleZijlstra** [python/typing#1174]
Python 3.11 will support generic NamedTuples (python/cpython#92027) and TypedDicts (python/cpython#27663) at runtime. If there is community interest, we should backport support for these features into typing-extensions. I'm not planning to work on this myself but I'll accept patches.

**Comment by Bluenix2** [comment]
As discovered in Python Discord's [`#type-hinting`](https://discord.com/channels/267624335836053506/891788761371906108/973230283132395570) channel, typing_extensions 4.2 release appears to support this already.

That said, it appears to still be missing for Python 3.7 and 3.8. [This CI run of mine is on Python 3.7](https://github.com/Bluenix2/discord-typings/runs/6431408319?check_suite_focus=true) and locally I can reproduce it on my Python 3.8.10 installaton (`py -3.8-64 -c "import discord_typings"`):
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\%username%\Projects\discord-typings\discord_typings\__init__.py", line 5, in <module> 
    from .gateway import *
  File "C:\Users\%username%\Projects\discord-typings\discord_typings\gateway.py", line 267, in <module>
    ReadyEvent = GenericDispatchEvent[Literal['READY'], ReadyData]
TypeError: '_TypedDictMeta' object is not subscriptable
```
