### ISSUE TITLE
ImportError: cannot import name 'Literal' from 'typing' (d:\user\documents\lib\typing.py)

### ISSUE THREAD

**Issue by Makpukich** [python/typing#1175]
trying to pip install requests in PowerShell
using python 3.8

PS D:\user\Documents> pip install typing
Traceback (most recent call last):
  File "d:\user\documents\lib\runpy.py", line 192, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "d:\user\documents\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "D:\user\Documents\Scripts\pip.exe\__main__.py", line 5, in <module>
  File "d:\user\documents\lib\site-packages\pip\_internal\cli\main.py", line 9, in <module>
    from pip._internal.cli.autocompletion import autocomplete
  File "d:\user\documents\lib\site-packages\pip\_internal\cli\autocompletion.py", line 10, in <module>
    from pip._internal.cli.main_parser import create_main_parser
  File "d:\user\documents\lib\site-packages\pip\_internal\cli\main_parser.py", line 8, in <module>
    from pip._internal.cli import cmdoptions
  File "d:\user\documents\lib\site-packages\pip\_internal\cli\cmdoptions.py", line 23, in <module>
    from pip._internal.cli.parser import ConfigOptionParser
  File "d:\user\documents\lib\site-packages\pip\_internal\cli\parser.py", line 12, in <module>
    from pip._internal.configuration import Configuration, ConfigurationError
  File "d:\user\documents\lib\site-packages\pip\_internal\configuration.py", line 20, in <module>
    from pip._internal.exceptions import (
  File "d:\user\documents\lib\site-packages\pip\_internal\exceptions.py", line 14, in <module>
    from pip._vendor.rich.console import Console, ConsoleOptions, RenderResult
  File "d:\user\documents\lib\site-packages\pip\_vendor\rich\console.py", line 36, in <module>
    from typing import Literal, Protocol, runtime_checkable
ImportError: cannot import name 'Literal' from 'typing' (d:\user\documents\lib\typing.py)

**Comment by srittau** [comment]
The `typing` module is part of Python 3.8, so trying to `pip install` it can't work. `pip install requests` is all you should need to install requests.
