### ISSUE TITLE
Strange mro order and __getitem__ method resolving

### ISSUE THREAD

**Issue by mitar** [python/typing#459]
```
>>> import inspect
>>> import typing
>>> inspect.getmro(typing.Sequence)
(typing.Sequence, <class 'collections.abc.Sequence'>, typing.Reversible, <class 'collections.abc.Reversible'>, typing.Collection, <class 'collections.abc.Collection'>, <class 'collections.abc.Sized'>, typing.Iterable, <class 'collections.abc.Iterable'>, typing.Container, <class 'collections.abc.Container'>, typing.Generic, <class 'object'>)
>>> typing.Sequence.__getitem__(1)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: __getitem__() missing 1 required positional argument: 'index'
>>> typing.Sequence[1]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/typing.py", line 682, in inner
    return func(*args, **kwds)
  File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/typing.py", line 1128, in __getitem__
    params = tuple(_type_check(p, msg) for p in params)
  File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/typing.py", line 1128, in <genexpr>
    params = tuple(_type_check(p, msg) for p in params)
  File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/typing.py", line 374, in _type_check
    raise TypeError(msg + " Got %.100r." % (arg,))
TypeError: Parameters to generic types must be types. Got 1.
```

`_getitem__` does not resolve the same as `[]` so it is not possible to get to `_getitem__.__wrapped__` to bypass the cache.

**Comment by mitar** [comment]
Ignore. This works:

```
type(typing.Sequence).__getitem__(typing.Sequence, 1)
```
