### ISSUE TITLE
snehu2015@gmail.com

### ISSUE THREAD

**Issue by snehasiby** [python/typing#620]
TypeError: descriptor '__subclasses__' of 'type' object needs an argument
Makefile:31: recipe for target 'train-core' failed
make: *** [train-core] Error 1

**Comment by JukkaL** [comment]
It's not clear what this issue is about.

**Comment by snehasiby** [comment]
python -m rasa_core.train -d domain.yml -s data/stories.md -o models/current/dialogue -c policies.yml
Traceback (most recent call last):
File "/usr/lib/python3.5/runpy.py", line 184, in _run_module_as_main
"main", mod_spec)
File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
exec(code, run_globals)
File "/home/annie/.virtualenvs/test3/lib/python3.5/site-packages/rasa_core/train.py", line 6, in
from rasa_core import config, cli
File "/home/annie/.virtualenvs/test3/lib/python3.5/site-packages/rasa_core/config.py", line 6, in
from rasa_core.policies import PolicyEnsemble
File "/home/annie/.virtualenvs/test3/lib/python3.5/site-packages/rasa_core/policies/init.py", line 1, in
from rasa_core.policies.policy import Policy
File "/home/annie/.virtualenvs/test3/lib/python3.5/site-packages/rasa_core/policies/policy.py", line 7, in
from rasa_core.domain import Domain
File "/home/annie/.virtualenvs/test3/lib/python3.5/site-packages/rasa_core/domain.py", line 11, in
from rasa_core.actions import Action, action
File "/home/annie/.virtualenvs/test3/lib/python3.5/site-packages/rasa_core/actions/init.py", line 1, in
from rasa_core.actions.action import Action
File "/home/annie/.virtualenvs/test3/lib/python3.5/site-packages/rasa_core/actions/action.py", line 9, in
from rasa_core import events
File "/home/annie/.virtualenvs/test3/lib/python3.5/site-packages/rasa_core/events/init.py", line 72, in
class Event(object):
File "/home/annie/.virtualenvs/test3/lib/python3.5/site-packages/rasa_core/events/init.py", line 93, in Event
default: Optional[Type['Event']] = None
File "/usr/lib/python3.5/typing.py", line 649, in getitem
return Union[arg, type(None)]
File "/usr/lib/python3.5/typing.py", line 552, in getitem
dict(self.dict), parameters, _root=True)
File "/usr/lib/python3.5/typing.py", line 512, in new
for t2 in all_params - {t1} if not isinstance(t2, TypeVar)):
File "/usr/lib/python3.5/typing.py", line 512, in
for t2 in all_params - {t1} if not isinstance(t2, TypeVar)):
File "/usr/lib/python3.5/typing.py", line 1077, in subclasscheck
if super().subclasscheck(cls):
File "/home/annie/.virtualenvs/test3/lib/python3.5/abc.py", line 225, in subclasscheck
for scls in cls.subclasses():
TypeError: descriptor 'subclasses' of 'type' object needs an argument
Makefile:31: recipe for target 'train-core' failed
make: *** [train-core] Error 1

Followed directions and installed dependencies via requirements.txt. I'm getting the above error running
'make train-core'.

And I am using
python version:- python3.5.2
os:- lubuntu 16.04.1

**Comment by gvanrossum** [comment]
You have the wrong project.

**Comment by ethanhs** [comment]
FWIW, if you look at the traceback, the exception is from the typing module. I tested and was able to repro the following fails on Python 3.5.2:

```
def test(t: Optional[Type['test']]): ...
```
with a similar traceback.

However, I *also* tested this on Python 3.5.7, and it appears this was fixed. So @snehasiby you need to upgrade your version of Python.
