### ISSUE TITLE
NameError: name 'Clazz' is not defined

### ISSUE THREAD

**Issue by urain39** [python/typing#714]
My code:
```py
class Clazz():
	def method(self) -> Clazz:
		return self

Clazz().method().method()
```

My mypy config:
```ini
[mypy]
strict=true
```

Run log
```log
$ mypy test2.py
Success: no issues found in 1 source file
$ python test2.py
Traceback (most recent call last):
  File "test2.py", line 1, in <module>
    class Clazz():
  File "test2.py", line 2, in Clazz
    def method(self) -> Clazz:
NameError: name 'Clazz' is not defined
```

My Python version:
```sh
$ python -V
Python 3.8.2
```

**Comment by gvanrossum** [comment]
This is a well-known limitation. Use -> 'Clazz' instead.

**Comment by urain39** [comment]
Ok thank you very much for your reply.
