### ISSUE TITLE
Defining subprotocols with AsyncContextManager in python < 3.8 raises a TypeError

### ISSUE THREAD

**Issue by HeavenVolkoff** [python/typing#720]
Creating a subprotocol with `AsyncContextManager` in python 3.8 works properly:
```python
from typing_extensions import Protocol, AsyncContextManager

class Example(AsyncContextManager, Protocol):
    test: str
```

However in python < 3.8 (Actually only tested in Python 3.6 and 3.7) the above raises a `TypeError`:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.7/abc.py", line 126, in __new__
    cls = super().__new__(mcls, name, bases, namespace, **kwargs)
  File "/usr/local/lib/python3.7/typing.py", line 847, in __init_subclass__
    super().__init_subclass__(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/typing_extensions.py", line 1541, in __init_subclass__
    ' protocols, got %r' % base)
TypeError: Protocols can only inherit from other protocols, got <class 'contextlib.AbstractAsyncContextManager'>
```

**Comment by JelleZijlstra** [comment]
This still fails but now with a slightly different error:
```
Traceback (most recent call last):
  File ".../python3.6/site-packages/IPython/core/interactiveshell.py", line 3343, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-19-79b240674311>", line 1, in <module>
    class Example(AsyncContextManager, Protocol):
  File ".../python3.6/site-packages/typing_extensions.py", line 790, in __init__
    raise TypeError(f'Protocols can only inherit from other'
TypeError: Protocols can only inherit from other protocols, got typing.AsyncContextManager
```
It is, of course, because Protocols didn't exist in 3.6/3.7 yet and therefore AsyncContextManager wasn't a Protocol.

We could fix this by duplicating the definition of AsyncContextManager and a number of other classes in typing-extensions and defining them as Protocols. However, this is a somewhat marginal use case, it's easy to work around (just write out the `__aenter__`/`__aexit__` methods yourself), and it affects only old versions of Python, so I'm inclined to close this as won't fix.

If someone cares about this issue and is willing to submit a PR fixing it, I will consider it.
