### ISSUE TITLE
AttributeError: module 'package.module' has no attribute 'attribute' on cyclic import with annotations 

### ISSUE THREAD

**Issue by mde-pach** [python/typing#743]
When I make a cyclic import for typing annotation needs, I got an AtributeError at runtime:

```
some_package
├── __init__.py
├── bar.py
└── foo.py
```
___
```python
$> cat some_package/bar.py
from . import foo

class Bar:
    def return_data(self, arg: foo.Data) -> Data:  # use foo.Data for typing annotation
        return Data()

class Data:
    pass
```
```python
$> cat some_package/bar.py
from . import bar

class Foo:
    def __init__(self) -> None:
        self._bar = bar.Bar()

    def return_data(self) -> bar.Data: # use bar.Data for typing annotation
        self._bar.return_data(Data())

class Data:
    pass
```
___
```
$> python3
>>> from some_package import bar
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/some_package /bar.py", line 1, in <module>
    from . import foo
  File "/some_package /foo.py", line 3, in <module>
    class Foo:
  File "/some_package /foo.py", line 7, in Foo
    def return_data(self) -> bar.Data:
AttributeError: module 'some_package.bar' has no attribute 'Data'
>>>
```
___
It looks like a strange behavior and I though even if it was due to a misuse of I, I could reference it here.

**Comment by gvanrossum** [comment]
That's due to import cycles and has little to do with the typing module or annotations. However, using `from __future__ import annotations` should remove the problem. Alternatively, you can put the offending annotations in string quotes (forward references per PEP 484). Both approaches solve the problem by not evaluating the annotations at runtime.
