### ISSUE TITLE
SyntaxError using List[X] when X overrides __new__

### ISSUE THREAD

**Issue by mxr** [python/typing#759]
Sorry for the terse report, I don't have a ton of context as to what's happening. Worked with @rkm for the repro and a potential root cause - reposting those thoughts:

> it's the `__new__` override that causes it I think... the typing code tries to ensure the variable is wrapped in a tuple by checking isinstance, which results in an empty string being passed to the _type_check method

Original repro:

```python
from typing import List
from unittest.mock import call


def f(n: List[call]) -> None:
    return None
```

A more minimal repro:

```python
from typing import List

class T(tuple):
    def __new__(cls):
        return tuple.__new__(cls, ("",))

t = T()
def f(a: List[t]):
    pass
```

---

When running the minimal repro:

```console
$ python example.py
Traceback (most recent call last):
  File "/Users/mxr/.pyenv/versions/3.6.10/lib/python3.6/typing.py", line 227, in __init__
    code = compile(arg, '<string>', 'eval')
  File "<string>", line 0

    ^
SyntaxError: unexpected EOF while parsing

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "example.py", line 8, in <module>
    def f(a: List[t]):
  File "/Users/mxr/.pyenv/versions/3.6.10/lib/python3.6/typing.py", line 679, in inner
    return cached(*args, **kwds)
  File "/Users/mxr/.pyenv/versions/3.6.10/lib/python3.6/typing.py", line 1107, in __getitem__
    params = tuple(_type_check(p, msg) for p in params)
  File "/Users/mxr/.pyenv/versions/3.6.10/lib/python3.6/typing.py", line 1107, in <genexpr>
    params = tuple(_type_check(p, msg) for p in params)
  File "/Users/mxr/.pyenv/versions/3.6.10/lib/python3.6/typing.py", line 369, in _type_check
    arg = _ForwardRef(arg)
  File "/Users/mxr/.pyenv/versions/3.6.10/lib/python3.6/typing.py", line 230, in __init__
    (arg,))
SyntaxError: Forward reference must be an expression -- got ''
```

---

My env:

[Platform info](https://github.com/asottile/scratch/wiki/platforms):

- **`sys.version`**: `'3.6.10 (default, May  3 2020, 20:12:12) \n[GCC 4.2.1 Compatible Apple LLVM 10.0.1 (clang-1001.0.46.4)]'`
- **`os.name`**: `'posix'`
- **`sys.platform`**: `'darwin'`
- **`platform.system()`**: `'Darwin'`
- **`platform.python_implementation()`**: `'CPython'`
- **`sys.implementation.name`**: `'cpython'`
- **`sysconfig.get_platform()`**: `'macosx-10.14-x86_64'`

Typing version:

```console
$ pip freeze | rg typing
typing==3.7.4.3
typing-inspect==0.6.0
```

**Comment by gvanrossum** [comment]
Is this still an issue if you uninstall typing? There is a good typing module in the stdlib.

**Comment by gvanrossum** [comment]
And what above newer Pythons?

**Comment by mxr** [comment]
> Is this still an issue if you uninstall typing? There is a good typing module in the stdlib.

I ran `pip uninstall -y typing typing-inspect` and could still repro the issue

```console
$ python example.py
Traceback (most recent call last):
  File "/Users/mxr/.pyenv/versions/3.6.10/lib/python3.6/typing.py", line 227, in __init__
    code = compile(arg, '<string>', 'eval')
  File "<string>", line 0

    ^
SyntaxError: unexpected EOF while parsing

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "example.py", line 8, in <module>
    def f(a: List[t]):
  File "/Users/mxr/.pyenv/versions/3.6.10/lib/python3.6/typing.py", line 679, in inner
    return cached(*args, **kwds)
  File "/Users/mxr/.pyenv/versions/3.6.10/lib/python3.6/typing.py", line 1107, in __getitem__
    params = tuple(_type_check(p, msg) for p in params)
  File "/Users/mxr/.pyenv/versions/3.6.10/lib/python3.6/typing.py", line 1107, in <genexpr>
    params = tuple(_type_check(p, msg) for p in params)
  File "/Users/mxr/.pyenv/versions/3.6.10/lib/python3.6/typing.py", line 369, in _type_check
    arg = _ForwardRef(arg)
  File "/Users/mxr/.pyenv/versions/3.6.10/lib/python3.6/typing.py", line 230, in __init__
    (arg,))
SyntaxError: Forward reference must be an expression -- got ''
```

---

> And what above newer Pythons?

Yes. No venv, but see below:

```console
$ ~/.pyenv/versions/3.7.3/bin/python3.7 example.py
Traceback (most recent call last):
  File "/Users/mxr/.pyenv/versions/3.7.3/lib/python3.7/typing.py", line 446, in __init__
    code = compile(arg, '<string>', 'eval')
  File "<string>", line 0

    ^
SyntaxError: unexpected EOF while parsing

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "example.py", line 8, in <module>
    def f(a: List[t]):
  File "/Users/mxr/.pyenv/versions/3.7.3/lib/python3.7/typing.py", line 248, in inner
    return cached(*args, **kwds)
  File "/Users/mxr/.pyenv/versions/3.7.3/lib/python3.7/typing.py", line 626, in __getitem__
    params = tuple(_type_check(p, msg) for p in params)
  File "/Users/mxr/.pyenv/versions/3.7.3/lib/python3.7/typing.py", line 626, in <genexpr>
    params = tuple(_type_check(p, msg) for p in params)
  File "/Users/mxr/.pyenv/versions/3.7.3/lib/python3.7/typing.py", line 129, in _type_check
    return ForwardRef(arg)
  File "/Users/mxr/.pyenv/versions/3.7.3/lib/python3.7/typing.py", line 448, in __init__
    raise SyntaxError(f"Forward reference must be an expression -- got {arg!r}")
SyntaxError: Forward reference must be an expression -- got ''
```

```console
$ ~/.pyenv/versions/3.8.2/bin/python3.8 example.py
Traceback (most recent call last):
  File "/Users/mxr/.pyenv/versions/3.8.2/lib/python3.8/typing.py", line 500, in __init__
    code = compile(arg, '<string>', 'eval')
  File "<string>", line 0

    ^
SyntaxError: unexpected EOF while parsing

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "example.py", line 8, in <module>
    def f(a: List[t]):
  File "/Users/mxr/.pyenv/versions/3.8.2/lib/python3.8/typing.py", line 258, in inner
    return cached(*args, **kwds)
  File "/Users/mxr/.pyenv/versions/3.8.2/lib/python3.8/typing.py", line 682, in __getitem__
    params = tuple(_type_check(p, msg) for p in params)
  File "/Users/mxr/.pyenv/versions/3.8.2/lib/python3.8/typing.py", line 682, in <genexpr>
    params = tuple(_type_check(p, msg) for p in params)
  File "/Users/mxr/.pyenv/versions/3.8.2/lib/python3.8/typing.py", line 139, in _type_check
    return ForwardRef(arg)
  File "/Users/mxr/.pyenv/versions/3.8.2/lib/python3.8/typing.py", line 502, in __init__
    raise SyntaxError(f"Forward reference must be an expression -- got {arg!r}")
SyntaxError: Forward reference must be an expression -- got ''
```

**Comment by gvanrossum** [comment]
In that case could you file a bug on bugs.python.org? 

Also, I am AFK, but maybe this is just something you shouldn’t do?

**Comment by mxr** [comment]
Looking closer I probably want to use `List[T]` or `List[_Call]` so maybe there is no action needed here after all 😄 thanks again!
