### ISSUE TITLE
test fails with Python 3.10.0a2

### ISSUE THREAD

**Issue by hegjon** [python/typing#766]
```
======================================================================
FAIL: test_keys_inheritance (__main__.TypedDictTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/builddir/build/BUILD/typing_extensions-3.7.4.3/src_py3/test_typing_extensions.py", line 1568, in test_keys_inheritance
    assert BaseAnimal.__annotations__ == {'name': str}
AssertionError

======================================================================
FAIL: test_py36_class_syntax_usage (__main__.TypedDictTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/builddir/build/BUILD/typing_extensions-3.7.4.3/src_py3/test_typing_extensions.py", line 1519, in test_py36_class_syntax_usage
    self.assertEqual(LabelPoint2D.__annotations__, {'x': int, 'y': int, 'label': str})
AssertionError: {'x': ForwardRef('int'), 'y': ForwardRef('int'), 'label': <class 'str'>} != {'x': <class 'int'>, 'y': <class 'int'>, 'label': <class 'str'>}
- {'label': <class 'str'>, 'x': ForwardRef('int'), 'y': ForwardRef('int')}
+ {'label': <class 'str'>, 'x': <class 'int'>, 'y': <class 'int'>}

----------------------------------------------------------------------
Ran 130 tests in 0.082s
```

See more details here https://bugzilla.redhat.com/show_bug.cgi?id=1900767

**Comment by gvanrossum** [comment]
Can you suggest a PR?

**Comment by gvanrossum** [comment]
Note that this is presumably,due to PEP 563 becoming the default in 3.10.

**Comment by noelevans** [comment]
PR #768 fixes this ticket (note the CLA won't be acknowledged until the next US business day)
