### ISSUE TITLE
When I ran this code i got this proplem

### ISSUE THREAD

**Issue by Mody213** [python/typing#787]
```
`from PyQt5.QtWidgets import *
from PyQt5.uic import loadUi
import sys
import mysql.connector
from win10toast import ToastNotifier

app = QApplication(sys.argv)

class Main(QMainWindow):
    def __init__(self):
        super().__init__()
        loadUi("main.ui", self)
        self.show()
        self.functions()
    
    #handeling every thing
    
    def Db_Connect(self):
        ## coneection between app and DB
        self.db = mysql.connector.connect(host='localhost' ,user='xxx', password='xxx', db='xxx')
        self.cur = self.db.cursor()
        print('Connection Accepted')
    
    def functions(self):
        self.Show_All_Types()
        self.Show_All_Products()
        self.Show_All_employees()
        self.btns()
        self.functions()
        self.UiChanges()
    
 
    def btns(self):
        self.pushButton.clicked.connect(self.Open_Product_Tab)
        self.pushButton_3.clicked.connect(self.Open_Calculator_Tab)
        self.pushButton_2.clicked.connect(self.Login)
        self.pushButton_40.clicked.connect(self.Show_All_Products)
        self.pushButton_41.clicked.connect(self.Add_New_Product)
        self.pushButton_50.clicked.connect(self.Delete_Product)
        self.pushButton_49.clicked.connect(self.Edit_Product)
        self.pushButton_48.clicked.connect(self.Edit_Product_search)
        self.pushButton_7.clicked.connect(self.Open_Setting_Tab)
        self.pushButton_4.clicked.connect(self.Add_New_Employee)
        self.pushButton_200.clicked.connect(self.Logout)
        self.pushButton_6.clicked.connect(self.Edit_employee)
        self.pushButton_8.clicked.connect(self.Delete_employee)
        self.pushButton_11.clicked.connect(self.Edit_employee_search)
        self.pushButton_5.clicked.connect(self.Open_Employees_Tab)
        self.pushButton_9.clicked.connect(self.Open_Sell_Tab)
        self.pushButton_48.clicked.connect(self.Show_All_employees)
        self.pushButton_13.clicked.connect(self.Edit_admin)
        self.pushButton_10.clicked.connect(self.Add_Type)
     

    def Open_Product_Tab(self):
         self.tabWidget.setCurrentIndex(1)
        
    def Open_Calculator_Tab(self):
         self.tabWidget.setCurrentIndex(3)   
        
    def Open_Sell_Tab(self):
         self.tabWidget.setCurrentIndex(2)   
        
    def Open_Employees_Tab(self):
         self.tabWidget.setCurrentIndex(4) 
        
    def Open_Setting_Tab(self):
         self.tabWidget.setCurrentIndex(5)  
    
    
    def UiChanges(self):
        self.tabWidget.tabBar().setVisible(False)
        self.tabWidget.setCurrentIndex(0)
    
    #logout and login    
    
    def Logout(self):
        pass
    
    def Login(self):
        username = self.lineEdit_4.text()
        password = self.lineEdit_2.text()


        self.cur.execute(""" SELECT id , password , password FROM employee""")
        data_ = self.cur.fetchall()

        for row in data_ :
            if row[1] == username and row[2] == password :
              self.pushButton_200.setVisible(True)
              self.pushButton.setEnabled(True)
              self.pushButton_3.setEnabled(True)
              self.tabWidget.setCurrentIndex(1) 
              self.label_7.setText("")
              self.pushButton_9.setEnabled(True)
              ToasNotifier = ToastNotifier()
              ToasNotifier.show_toast("Login", "You Are in The System", threaded=True, icon_path='D:\\Programing\\مشاريع\لم يكتمل بعد\\Super Market System\\Icons\\Not.ico', duration=3)
            else:
              self.label_7.setText("Error ^_^")
    #products
    
    def Show_All_Products(self):
        pass
        
    def Add_New_Product(self):
        pass
        
    def Delete_Product(self):
        pass
    
    def Edit_Product(self):
        pass
        
    def Edit_Product_search(self):
        pass
    
    #employees
    
    def Show_All_employees(self):
        pass
    
    def Add_New_Employee(self):
        pass
    
    def Edit_employee(self):
        pass
    
    def Delete_employee(self):
        pass
    
    def Edit_employee_search(self):
        pass
    
    #admin
    def Edit_admin(self):
        pass
        
    def admin(self):
        pass
    
    #types
    def Show_All_Types(self):
        pass
        
    def Add_Type(self):
        pass
        
    def Edit_Type(self):
        pass
        
    def Delete_type(self):
        pass

    
window = Main()

app.exec_()
```
`

how can i slove this proplem

```
Traceback (most recent call last):
  File "index.py", line 155, in <module>
    window = Main()
  File "index.py", line 14, in __init__
    self.functions()
  File "index.py", line 29, in functions
    self.functions()
  File "index.py", line 29, in functions
    self.functions()
  File "index.py", line 29, in functions
    self.functions()
  [Previous line repeated 990 more times]
  File "index.py", line 28, in functions
    self.btns()
  File "index.py", line 34, in btns
    self.pushButton.clicked.connect(self.Open_Product_Tab)
RecursionError: maximum recursion depth exceeded while calling a Python object
```

**Comment by JelleZijlstra** [comment]
This has nothing to do with `typing`. Perhaps ask on StackOverflow.
