### ISSUE TITLE
Possibly buggy behavior with `get_type_hints`, multiple classes, and forward reference

### ISSUE THREAD

**Issue by 2435191** [python/typing#793]
The following is a minimum working example; the problem I'm actually working on is much more complex.

Let's say I have a file `my_int.py` in which I define some dummy class:
```
class MyInt(int):
    pass
```
Also define another class in `my_class.py` that relies on `MyInt` for type hinting, but for whatever reason cannot `import my_int` (in my case, circular import). In this case I would use `annotations` from `__future__`:
```
from __future__ import annotations
# from my_int import MyInt <- can't do this

class MyClass:
    my_param: MyInt = 0
```

Then if I try to run the following code in a driver file (or in `my_class.py`, same result), I get a `NameError`:
```
from typing import get_type_hints
from my_class import MyClass

print(get_type_hints(MyClass))
```
```
Traceback (most recent call last):
  File "[redacted]/my_class.py", line 7, in <module>
    print(get_type_hints(MyClass))
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/typing.py", line 1229, in get_type_hints
    value = _eval_type(value, base_globals, localns)
  File "[redacted]/typing.py", line 270, in _eval_type
    return t._evaluate(globalns, localns)
  File "[redacted]/typing.py", line 518, in _evaluate
    eval(self.__forward_code__, globalns, localns),
  File "<string>", line 1, in <module>
NameError: name 'MyInt' is not defined
```
If I `from my_int import MyInt`, it works... but I can't do that. I tried messing around with `globalns` and `localns` or defining `MyInt = "MyInt"`, but the former was really ugly/repetitive and `typing` didn't properly resolve the forward reference in the latter. Any pointers would be appreciated, although I've already RTFD. Thanks!

EDIT: After thinking about it, I conclude the issue is not resolving forward references before using them, which is weird because that behavior usually happens. I'll look into the source code.

**Comment by 2435191** [comment]
Figured it out after looking at source. Just set `globalns = globals()` in `get_type_hints`. (In my example, I also should have had `from my_int import MyInt` in the driver code— did that in the real thing, though.)
