### ISSUE TITLE
telethon library of python error

### ISSUE THREAD

**Issue by foxhacker0000** [python/typing#809]
Traceback (most recent call last):
  File "C:\Users\Fox-Hacker\Desktop\t-adder\scrapper.py", line 12, in <module>
    from telethon.sync import TelegramClient
  File "C:\Users\Fox-Hacker\AppData\Local\Programs\Python\Python310\lib\site-packages\telethon\__init__.py", line 1, in <module>
    from .client.telegramclient import TelegramClient
  File "C:\Users\Fox-Hacker\AppData\Local\Programs\Python\Python310\lib\site-packages\telethon\client\__init__.py", line 12, in <module>
    from .telegrambaseclient import TelegramBaseClient
  File "C:\Users\Fox-Hacker\AppData\Local\Programs\Python\Python310\lib\site-packages\telethon\client\telegrambaseclient.py", line 12, in <module>
    from ..entitycache import EntityCache
  File "C:\Users\Fox-Hacker\AppData\Local\Programs\Python\Python310\lib\site-packages\telethon\entitycache.py", line 47, in <module>
    _fill()
  File "C:\Users\Fox-Hacker\AppData\Local\Programs\Python\Python310\lib\site-packages\telethon\entitycache.py", line 43, in _fill
    raise RuntimeError('FIXME: Did the init signature or updates change?')
RuntimeError: FIXME: Did the init signature or updates change?

**Comment by hauntsaninja** [comment]
Probably should be filed on the telethon library's issue tracker
